spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8000

kafka:
  topic:
    activateAccount: activate_account
    resetPassword: reset_password
  bootstrapAddress: kafka:9092

gymapp:
  activation:
    url: http://localhost:8080/activate
  resetPassword:
    url: http://localhost:8080/reset-password
  email: ${GYM_APP_EMAIL}