server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
jwt:
  secret: ${JWT_TOKEN}
  issuer: malewicz.jakub.user_service
