spring:
  application:
    name: exercise-service
  datasource:
    url: jdbc:postgresql://app-db:5432/postgres?currentSchema=exercises
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate


eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
server:
  port: 8060
