spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
jwt:
  secret: ${JWT_SECRET}
  issuer: malewicz.jakub.user_service
  expiration: 10
forgotPassword:
  token:
    ttl-seconds: 1200
    length: 36

kafka:
  topics:
    resetPassword: reset_password
    activateAccount: activate_account