server:
  port: 8070
spring:
  application:
    name: statistics-service
  datasource:
    url: jdbc:postgresql://app-db:5432/postgres?currentSchema=statistics
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  cloud:
    openfeign:
      client:
        config:
          default:
            errorDecoder: malewicz.jakub.statistics_service.clients.FeignErrorDecoder
      circuitbreaker:
        enabled: true
  data:
    jdbc:
      dialect: h2

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka