server:
  port: 8070
spring:
  application:
    name: statistics-service
  datasource:
    url: jdbc:h2:mem:statistics
  cloud:
    openfeign:
      client:
        config:
          default:
            errorDecoder: malewicz.jakub.statistics_service.clients.FeignErrorDecoder

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}