spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=statistics
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka