services:
  app-db:
    image: postgres:latest
    container_name: workout-app-dp
    env_file:
      - .env
    ports:
      - "5432:5432"
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://app-db/postgres -user=postgres -password=postgres -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - app-db
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  eureka:
    build:
      context: ../discovery-server
    develop:
      watch:
        - action: rebuild
          path: ../discovery-server/src
          target: /app/src
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ../api-gateway
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ../api-gateway/src
          target: /app/src
    ports:
      - "9000:9000"
    depends_on:
      - eureka

  exercise-service:
    build:
      context: ../exercise-service
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ../exercise-service/src
          target: /app/src
    ports:
      - "8060:8060"
    depends_on:
      - eureka
      - app-db

  user-service:
    build:
      context: ../user-service
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ../user-service/src
          target: /app/src
    ports:
      - "8080:8080"
    depends_on:
      - app-db
      - kafka
      - eureka

  notification-service:
    build:
      context: ../notification-service
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ../notification-service/src
          target: /app/src
    ports:
      - "8000:8000"
    depends_on:
      - eureka
      - kafka

  statistics-service:
    build:
      context: ../statistics-service
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ../statistics-service/src
          target: /app/src
    ports:
      - "8070:8070"
    depends_on:
      - eureka
      - app-db

  workout-service:
    build:
      context: ../workout-service
    env_file:
      - .env
    develop:
      watch:
        - action: rebuild
          path: ../workout-service/src
          target: /app/src
    ports:
      - "8090:8090"
    depends_on:
      - eureka
      - app-db
