name: Api-Gateway Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - api-gateway/**
  pull_request:
    branches: [ "main" ]
    paths:
      - api-gateway/**

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Run tests for api-gateway
        run: gradle --no-daemon test
        working-directory: api-gateway/