name: Exercise-Service Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - exercise-service/**
  pull_request:
    branches: [ "main" ]
    paths:
      - exercise-service/**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Run tests for exercise-service
        run: gradle --no-daemon test
        working-directory: exercise-service/