name: User-Service Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - user-service/**
  pull_request:
    branches: [ "main" ]
    paths:
      - user-service/**

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Run tests for user-service
        run: gradle --no-daemon test
        working-directory: user-service/