name: Workout-Service Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - workout-service/**
  pull_request:
    branches: [ "main" ]
    paths:
      - workout-service/**

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0
        options: --privileged
        ports:
          - 2375:2375

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Run tests for workout-service
        run: gradle --no-daemon test
        working-directory: workout-service/