server:
  port: 8090

spring:
  application:
    name: workout-service
  datasource:
    url: jdbc:h2:mem:workouts
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

