server:
  port: 8090

spring:
  application:
    name: workout-service
  datasource:
    url: jdbc:postgresql://app-db:5432/postgres?currentSchema=workouts
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  cloud:
    openfeign:
      client:
        config:
          default:
            errorDecoder: malewicz.jakub.workout_service.clients.FeignErrorDecoder

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

